### ISSUE TITLE
OSX: El Capitan

### ISSUE THREAD

**Issue by DanyelSuxdorf** [TobiasMende/TeXtended#3]
Doesn't work on OS X El Capitan. Changed the texbin-path to "/Library/TeX/texbin". TexTended found the compilers but it won't compile. No errors shown.

El Capitan changes:
https://tug.org/mactex/elcapitan.html

**Comment by TobiasMende** [comment]
The path to the texbin directory has changed with MacTex 2015. Therefore, also the compiler scripts must be updated. For clean installations of TeXtended, this will be fixed in version 0.12.

**Comment by y1337x** [comment]
The new version works pretty well and fixed the El Capitan error. Nice work, thanks!
